app:
    resource: '@AppBundle/Controller/'
    type: annotation

homepage:
    path: /
    defaults:
        _controller: AppBundle:Menu:index

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"