<?php


namespace AppBundle\Twig;


class MarkdownExtension extends \Twig_Extension
{
    public function getFilters()
    {
        return parent::getFilters(); // TODO: Change the autogenerated stub
    }

    public function getName()
    {
        return parent::getName(); // TODO: Change the autogenerated stub
    }


}